name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_USER: ${{ secrets.VPS_SSH_USER }}
      SSH_HOST: ${{ secrets.VPS_SSH_HOST }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: actions/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to VPS
        run: |
          rsync -avz --delete --exclude='.git' ./ $SSH_USER@$SSH_HOST:/var/www/genesis-case-task/

      - name: Run Docker Compose on VPS
        run: |
          ssh $SSH_USER@$SSH_HOST << 'EOF'
            cd /var/www/genesis-case-task/
            docker-compose pull
            docker-compose up -d --build --force-recreate
          EOF
